# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "my-sam-boilerplate"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"

[dev.deploy.parameters]
stack_name = "my-api-dev"
resolve_s3 = true
s3_prefix = "my-api-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=dev DBName=MyDatabaseDev DBMasterUsername=admin_dev AllowedOrigin='*'"

[prod.deploy.parameters]
stack_name = "my-api-prod"
resolve_s3 = true
s3_prefix = "my-api-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "Environment=prod DBName=MyDatabaseProd DBMasterUsername=admin_prod AllowedOrigin='http://localhost:3000'"


[dev.global.parameters]
region = "us-east-1"

[prod.global.parameters]
region = "us-east-1"

[dev.sync.parameters]
watch = true

[prod.sync.parameters]
watch = false